###
https://localhost:7064/cliente/reporte/puntos
###
https://localhost:7064/cliente/reporte/lavados/25325241
###
https://localhost:7064/cliente/reporte/plantilla
###
https://localhost:7064/cliente/facturacion/3

###
https://localhost:7064/cliente/get_all
