###
http://localhost:5064/reportes/puntos
###
http://localhost:5064/reportes/lavados/25325241
###
http://localhost:5064/reportes/planilla
###
http://localhost:5064/reportes/facturacion/1
###
http://localhost:5064/cliente/importar_clientes
###
http://localhost:5064/cliente/get_all
###
http://localhost:5064/cliente/get/53294589
###
http://localhost:5064/trabajador/get_all
###
http://localhost:5064/sucursal/get_all
###
http://localhost:5064/sucursal/get/1
###
http://localhost:5064/proveedor/get/1234567811