GO
DROP TABLE PRODUCTOS_POR_SUCURSAL
GO
DROP TABLE PRODUCTOS_POR_CLIENTE
GO
DROP TABLE PRODUCTO
GO
DROP TABLE CONTACTO_PROVEEDOR
GO
DROP TABLE PROVEEDOR
GO
DROP TABLE TRABAJADORES_POR_CITA
GO
DROP TABLE CITA
GO
DROP TABLE DIRECCIONES_CLIENTE
GO
DROP TABLE TELEFONOS_CLIENTE
GO
DROP TABLE CLIENTE
GO
DROP TABLE LAVADO
GO
DROP TABLE SUCURSAL
GO
DROP TABLE TRABAJADOR